### ISSUE TITLE
No module named '_core'

### ISSUE THREAD

**Issue by iwatobipen** [lich-uct/molpher-lib#9] opened 2019-11-20 01:57 UTC
Hi,
I created new environment of conda and install molpher-lib via conda command.
But I got following error when I call the package from python.

ModuleNotFoundError: No module named '_core'

How can I fix the problem?
Any comments or advices are greatly appreciated.
Thanks,

**Comment by martin-sicho** [comment] 2019-11-20 19:52
Some dependencies have changed since the last build which caused this error. I rectified the issues already, but did not merge those changes to the master branch yet. In the meantime, you can try the latest development snapshot. You can install it like this:

```python
conda install -c lich/label/dev molpher-lib
```

The last one is very similar to the previous beta and should be stable. Let me know if the problem persists and I will look into this in more detail.

**Comment by iwatobipen** [comment] 2019-11-29 12:57
Thanks for your kind reply! I'll try it．

**Comment by stevenkbennett** [comment] 2020-01-28 12:14
Hi, I'm also receiving the same issue after installing via the command posted above.
Any help would be appreciated!

**Comment by martin-sicho** [comment] 2020-01-29 11:12
Hi,

thanks for bringing this to my attention. I tested in a clean environment and it seems that conda is having some problems resolving the package correctly if you try to install with just `conda install -c lich/label/dev molpher-lib`. It tries to install a rather old version instead of the newest one. It did not occur to me before. You should be able to force conda to install the latest snapshot manually, though:

```bash
conda install -c lich/label/dev molpher-lib=0.0.0b3.dev2
```

I compiled this one today. It has some performance boosts, but one operator still misbehaves a little in the python package. But you should be able to install 0.0.0b3.dev1 as well, which is more solid, but could be slower.

@iwatobipen Maybe this could help you as well?

**Comment by stevenkbennett** [comment] 2020-01-29 14:16
Hi, thanks for your quick reply! I tried installing both 0.0.0b3.dev2 and 0.0.0b3.dev1 in a new environment but received the same error.

**Comment by martin-sicho** [comment] 2020-01-29 14:29
No problem. Can you post a full traceback of the error? What version of rdkit are you using? Can you post the output of `conda list` for your environment? I will try to reproduce it on my end.

**Comment by stevenkbennett** [comment] 2020-01-29 14:43
After updating rdkit from rdkit-2018.03.4 to rdkit-2019.09.3.0 it now seems to work. Please also see attached the packages in my environment.

```# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.11.27                    0
cairo                     1.14.12              h8948797_3
certifi                   2019.11.28               py37_0
decorator                 4.4.1                      py_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
glib                      2.63.1               h5a9c865_0
icu                       58.2                 h9c2bf20_1
intel-openmp              2019.4                      243
ipython                   7.11.1           py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.16.0                   py37_0
jpeg                      9b                   h024ee3a_2
ld_impl_linux-64          2.33.1               h53a641e_7
libboost                  1.67.0               h46d08c1_4
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.15           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
molpher                   0.0.0b3.dev2             pypi_0    pypi
molpher-lib               0.0.0b3.dev2              py3_0    lich/label/dev
ncurses                   6.1                  he6710b0_1
numpy                     1.18.1           py37h4f9e942_0
numpy-base                1.18.1           py37hde5b4d6_1
olefile                   0.46                     py37_0
openssl                   1.1.1d               h7b6447c_3
pandas                    0.25.3           py37he6710b0_0
parso                     0.6.0                      py_0
pcre                      8.43                 he6710b0_0
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    7.0.0            py37hb39fc2d_0
pip                       20.0.2                   py37_0
pixman                    0.38.0               h7b6447c_0
prompt_toolkit            3.0.2                      py_0
ptyprocess                0.6.0                    py37_0
py-boost                  1.67.0           py37h04863e7_4
pygments                  2.5.2                      py_0
python                    3.7.6                h0371630_2
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
rdkit                     2019.09.3.0      py37hc20afe1_1    rdkit
readline                  7.0                  h7b6447c_5
setuptools                45.1.0                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.30.1               h7b6447c_0
tbb                       2019.8               hfd86e86_0
tk                        8.6.8                hbc83047_0
traitlets                 4.3.3                    py37_0
wcwidth                   0.1.7                    py37_0
wheel                     0.33.6                   py37_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0```

**Comment by martin-sicho** [comment] 2020-01-29 15:01
Great. RDKit was one of the dependencies that changed so it was likely the cause of the issue here. The names of the RDKit libraries changed some time ago so the dynamic linking broke.

I will mark this as closed once I am ready to merge to master again. If you run into more problems, let me know :)

**Closed as completed** 2021-10-21 10:11 UTC
Labels: bug
